### ISSUE TITLE
Request new Feature

### ISSUE THREAD

**Issue by Jahanzeb009** [pierreamgabriel/react-native-weather-api#1]
I appreciate your work and efforts

but It'll be very grateful for me or maybe for others

Please add 
3 hour forecast: 5 days API 

I make changes in your weather.js file and it's working fine but if you could do yourself and publish it would be very awesome

**Comment by pierreamgabriel** [comment]
> I appreciate your work and efforts
> 
> but It'll be very grateful for me or maybe for others
> 
> Please add 3 hour forecast: 5 days API
> 
> I make changes in your weather.js file and it's working fine but if you could do yourself and publish it would be very awesome

Added in the version 3.4.0. See docs.
